### ISSUE TITLE
License issue with INumerics

### ISSUE THREAD

**Issue by RoySalisbury** [ghilios/joko.nina.plugins#15]
This is for the 3.0 nightly...

---
System.TypeInitializationException: The type initializer for 'ILNumerics.Drawing.Scene' threw an exception.
 ---> System.ComponentModel.LicenseException: A valid license for the following ILNumerics component(s) could not be found for the assembly 'NINA.Joko.Plugins.HocusFocus, Version=3.0.0.13, Culture=neutral, PublicKeyToken=null'! Make sure that the assembly was built on a system which has a valid license for the components installed! Otherwise remove the reference(s) to the component(s) from the assembly and rebuild it!
ILNumerics.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9651adc37f12bb00
ILNumerics.Toolboxes.Optimization, Version=7.0.0.0, Culture=neutral, PublicKeyToken=d11317283e0d33b5
ILNumerics.Drawing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=e22c8a010c3b081a
ILNumerics.Computing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=8d9bf50ef854734d
ILNumerics.Drawing.Platforms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=0a23ecb2dfe3fc7e
ILNumerics.numpy, Version=7.0.0.0, Culture=neutral, PublicKeyToken=5191cdff9aceda71
ILNumerics.Toolboxes.Interpolation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=feb6e2cd77588932
   at ILNumerics.Licensing.LicenseManager.VerifyAssembly(Assembly assembly)
   at ILNumerics.Licensing.LicenseManager.VerifyAssemblies()
   at ILNumerics.Licensing.LicenseManager.get_AppDomainIsVerified()
   at ILNumerics.Licensing.RuntimeLicenseProvider.GetLicense(LicenseContext context, Type type, Object instance, Boolean allowExceptions)
   at System.ComponentModel.LicenseManager.ValidateInternalRecursive(LicenseContext context, Type type, Object instance, Boolean allowExceptions, License& license, String& licenseKey)
   at System.ComponentModel.LicenseManager.Validate(Type type)
   at ILNumerics.Drawing.Scene..cctor()
   --- End of inner exception stack trace ---
   at ILNumerics.Drawing.Scene..ctor(Boolean localScene)
   at NINA.Joko.Plugins.HocusFocus.Controls.SensorModelContourMapControl.GetScene() in C:\Users\ghili\src\joko.nina.plugins_3.0\Joko.NINA.Plugins\Joko.NINA.Plugins.HocusFocus\Controls\SensorModelContourMapControl.cs:line 286
2023-10-20T18:57:44.7140|ERROR|App.xaml.cs|Current_DispatcherUnhandledException|221|An unhandled exception has occurred of type System.TypeInitializationException
2023-10-20T18:57:44.7170|ERROR|App.xaml.cs|Current_DispatcherUnhandledException|224|The type initializer for 'ILNumerics.Drawing.Scene' threw an exception.
   at ILNumerics.Drawing.Scene..ctor(Boolean localScene)
   at NINA.Joko.Plugins.HocusFocus.Controls.SensorModelContourMapControl.GetScene() in C:\Users\ghili\src\joko.nina.plugins_3.0\Joko.NINA.Plugins\Joko.NINA.Plugins.HocusFocus\Controls\SensorModelContourMapControl.cs:line 286
   at NINA.Joko.Plugins.HocusFocus.Controls.ILNSceneControlBase.UpdateScene() in C:\Users\ghili\src\joko.nina.plugins_3.0\Joko.NINA.Plugins\Joko.NINA.Plugins.HocusFocus\Controls\ILNSceneControlBase.xaml.cs:line 180
   at NINA.Joko.Plugins.HocusFocus.Controls.SensorModelContourMapControl.OnAnyPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) in C:\Users\ghili\src\joko.nina.plugins_3.0\Joko.NINA.Plugins\Joko.NINA.Plugins.HocusFocus\Controls\SensorModelContourMapControl.cs:line 159
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Inner Exception of type System.ComponentModel.LicenseException: 
System.ComponentModel.LicenseException: A valid license for the following ILNumerics component(s) could not be found for the assembly 'NINA.Joko.Plugins.HocusFocus, Version=3.0.0.13, Culture=neutral, PublicKeyToken=null'! Make sure that the assembly was built on a system which has a valid license for the components installed! Otherwise remove the reference(s) to the component(s) from the assembly and rebuild it!
ILNumerics.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9651adc37f12bb00
ILNumerics.Toolboxes.Optimization, Version=7.0.0.0, Culture=neutral, PublicKeyToken=d11317283e0d33b5
ILNumerics.Drawing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=e22c8a010c3b081a
ILNumerics.Computing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=8d9bf50ef854734d
ILNumerics.Drawing.Platforms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=0a23ecb2dfe3fc7e
ILNumerics.numpy, Version=7.0.0.0, Culture=neutral, PublicKeyToken=5191cdff9aceda71
ILNumerics.Toolboxes.Interpolation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=feb6e2cd77588932
   at ILNumerics.Licensing.LicenseManager.VerifyAssembly(Assembly assembly)
   at ILNumerics.Licensing.LicenseManager.VerifyAssemblies()
   at ILNumerics.Licensing.LicenseManager.get_AppDomainIsVerified()
   at ILNumerics.Licensing.RuntimeLicenseProvider.GetLicense(LicenseContext context, Type type, Object instance, Boolean allowExceptions)
   at System.ComponentModel.LicenseManager.ValidateInternalRecursive(LicenseContext context, Type type, Object instance, Boolean allowExceptions, License& license, String& licenseKey)
   at System.ComponentModel.LicenseManager.Validate(Type type)
   at ILNumerics.Drawing.Scene..cctor()   at ILNumerics.Drawing.Scene..ctor(Boolean localScene)
   at NINA.Joko.Plugins.HocusFocus.Controls.SensorModelContourMapControl.GetScene() in C:\Users\ghili\src\joko.nina.plugins_3.0\Joko.NINA.Plugins\Joko.NINA.Plugins.HocusFocus\Controls\SensorModelContourMapControl.cs:line 286
   at NINA.Joko.Plugins.HocusFocus.Controls.ILNSceneControlBase.UpdateScene() in C:\Users\ghili\src\joko.nina.plugins_3.0\Joko.NINA.Plugins\Joko.NINA.Plugins.HocusFocus\Controls\ILNSceneControlBase.xaml.cs:line 180
   at NINA.Joko.Plugins.HocusFocus.Controls.SensorModelContourMapControl.OnAnyPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) in C:\Users\ghili\src\joko.nina.plugins_3.0\Joko.NINA.Plugins\Joko.NINA.Plugins.HocusFocus\Controls\SensorModelContourMapControl.cs:line 159
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2023-10-20T18:57:57.3347|INFO|HocusFocusStarDetection.cs|Detect|410|Average HFR: 2.020081974119554, HFR MAD: 0.21888808044097563, Detected Stars 12756, Region: 0
2023-10-20T18:57:58.7765|ERROR|TiltModelControl.cs|Failed updating scene|428
System.TypeInitializationException: The type initializer for 'ILNumerics.Drawing.Scene' threw an exception.
 ---> System.ComponentModel.LicenseException: A valid license for the following ILNumerics component(s) could not be found for the assembly 'NINA.Joko.Plugins.HocusFocus, Version=3.0.0.13, Culture=neutral, PublicKeyToken=null'! Make sure that the assembly was built on a system which has a valid license for the components installed! Otherwise remove the reference(s) to the component(s) from the assembly and rebuild it!
ILNumerics.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9651adc37f12bb00
ILNumerics.Toolboxes.Optimization, Version=7.0.0.0, Culture=neutral, PublicKeyToken=d11317283e0d33b5
ILNumerics.Drawing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=e22c8a010c3b081a
ILNumerics.Computing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=8d9bf50ef854734d
ILNumerics.Drawing.Platforms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=0a23ecb2dfe3fc7e
ILNumerics.numpy, Version=7.0.0.0, Culture=neutral, PublicKeyToken=5191cdff9aceda71
ILNumerics.Toolboxes.Interpolation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=feb6e2cd77588932
   at ILNumerics.Licensing.LicenseManager.VerifyAssembly(Assembly assembly)
   at ILNumerics.Licensing.LicenseManager.VerifyAssemblies()
   at ILNumerics.Licensing.LicenseManager.get_AppDomainIsVerified()
   at ILNumerics.Licensing.RuntimeLicenseProvider.GetLicense(LicenseContext context, Type type, Object instance, Boolean allowExceptions)
   at System.ComponentModel.LicenseManager.ValidateInternalRecursive(LicenseContext context, Type type, Object instance, Boolean allowExceptions, License& license, String& licenseKey)
   at System.ComponentModel.LicenseManager.Validate(Type type)
   at ILNumerics.Drawing.Scene..cctor()
   --- End of inner exception stack trace ---
   at ILNumerics.Drawing.Scene..ctor(Boolean localScene)
   at NINA.Joko.Plugins.HocusFocus.Controls.TiltModelControl.GetScene() in C:\Users\ghili\src\joko.nina.plugins_3.0\Joko.NINA.Plugins\Joko.NINA.Plugins.HocusFocus\Controls\TiltModelControl.cs:line 240
---

**Comment by ghilios** [comment]
Hey Roy, this is a known issue with the 7.X beta of ILNumerics. I had to upgrade to support .NET Core, and the author of ILNumerics refuses to fix this licensing issue.

If you use NINA 3.0, you need to disable graphics in Hocus Focus.
